import { TimelineModel } from '@/Components/Timeline/TimelineProvider/types'
import { mockGroups } from './MockGroup'
import { mockTimeEvents } from './MockTimeEvents'

export const mockTimelines: TimelineModel[] = [
    {
        id: 1,
        name: 'Marketing Timeline',
        description: 'Timeline for Marketing Events',
        creationDate: '2023-11-01 08:00:00',
        timeEvents: [mockTimeEvents[0], mockTimeEvents[1], mockTimeEvents[2]],
        group: mockGroups[0],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 2,
        name: 'Community Timeline',
        description: 'Timeline for Community Events',
        creationDate: '2023-11-02 09:30:00',
        timeEvents: [mockTimeEvents[3], mockTimeEvents[4], mockTimeEvents[5]],
        group: mockGroups[1],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 3,
        name: 'Tech Timeline',
        description: 'Timeline for Tech Events',
        creationDate: '2023-11-03 11:15:00',
        timeEvents: [mockTimeEvents[6], mockTimeEvents[7], mockTimeEvents[8]],
        group: mockGroups[2],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 4,
        name: 'Art Timeline',
        description: 'Timeline for Art Events',
        creationDate: '2023-11-04 13:45:00',
        timeEvents: [mockTimeEvents[9], mockTimeEvents[10], mockTimeEvents[11]],
        group: mockGroups[3],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 5,
        name: 'Family Timeline',
        description: 'Timeline for Family Events',
        creationDate: '2023-11-05 15:20:00',
        timeEvents: [
            mockTimeEvents[12],
            mockTimeEvents[13],
            mockTimeEvents[14],
        ],
        group: mockGroups[4],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 6,
        name: 'Adventure Timeline',
        description: 'Timeline for Outdoor Events',
        creationDate: '2023-11-06 17:10:00',
        timeEvents: [
            mockTimeEvents[15],
            mockTimeEvents[16],
            mockTimeEvents[17],
        ],
        group: mockGroups[5],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 7,
        name: 'Foodie Timeline',
        description: 'Timeline for Food Events',
        creationDate: '2023-11-07 18:45:00',
        timeEvents: [
            mockTimeEvents[18],
            mockTimeEvents[19],
            mockTimeEvents[20],
        ],
        group: mockGroups[6],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 8,
        name: 'Book Club Timeline',
        description: 'Timeline for Literary Events',
        creationDate: '2023-11-08 20:30:00',
        timeEvents: [
            mockTimeEvents[21],
            mockTimeEvents[22],
            mockTimeEvents[23],
        ],
        group: mockGroups[7],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 9,
        name: 'Wellness Club Timeline',
        description: 'Timeline for Fitness Events',
        creationDate: '2023-11-09 22:15:00',
        timeEvents: [
            mockTimeEvents[24],
            mockTimeEvents[25],
            mockTimeEvents[26],
        ],
        group: mockGroups[8],
        ownerEmail: 'email',
        category: null,
    },
    {
        id: 10,
        name: 'Education Enthusiasts Timeline',
        description: 'Timeline for Educational Seminars',
        creationDate: '2023-11-10 23:59:00',
        timeEvents: [
            mockTimeEvents[27],
            mockTimeEvents[28],
            mockTimeEvents[29],
        ],
        group: mockGroups[9],
        ownerEmail: 'email',
        category: null,
    },
]
