import { Group } from '@/Components/Group/GroupTypes'

export const mockUsers: any[] = [
    { id: 1, username: 'user1' },
    { id: 2, username: 'user2' },
    { id: 3, username: 'user3' },
    { id: 4, username: 'user4' },
    { id: 5, username: 'user5' },
    { id: 6, username: 'user6' },
    { id: 7, username: 'user7' },
    { id: 8, username: 'user8' },
    { id: 9, username: 'user9' },
    { id: 10, username: 'user10' },
    { id: 11, username: 'user11' },
    { id: 12, username: 'user12' },
    { id: 13, username: 'user13' },
    { id: 14, username: 'user14' },
    { id: 15, username: 'user15' },
    { id: 16, username: 'user16' },
    { id: 17, username: 'user17' },
    { id: 18, username: 'user18' },
    { id: 19, username: 'user19' },
    { id: 20, username: 'user20' },
    { id: 21, username: 'user21' },
    { id: 22, username: 'user22' },
    { id: 23, username: 'user23' },
    { id: 24, username: 'user24' },
    { id: 25, username: 'user25' },
    { id: 26, username: 'user26' },
    { id: 27, username: 'user27' },
    { id: 28, username: 'user28' },
    { id: 29, username: 'user29' },
    { id: 30, username: 'user30' },
]

export const mockGroups: Group[] = [
    {
        id: 1,
        name: 'Marketing Group',
        description: 'Group for Marketing Events',
        users: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[5]],
    },
    {
        id: 2,
        name: 'Community Group',
        description: 'Group for Community Events',
        users: [mockUsers[3], mockUsers[4], mockUsers[5], mockUsers[8]],
    },
    {
        id: 3,
        name: 'Tech Group',
        description: 'Group for Tech Events',
        users: [mockUsers[6], mockUsers[7], mockUsers[8], mockUsers[11]],
    },
    {
        id: 4,
        name: 'Art Group',
        description: 'Group for Art Events',
        users: [mockUsers[9], mockUsers[10], mockUsers[11], mockUsers[14]],
    },
    {
        id: 5,
        name: 'Family Group',
        description: 'Group for Family Events',
        users: [mockUsers[0], mockUsers[12], mockUsers[13], mockUsers[16]],
    },
    {
        id: 6,
        name: 'Adventure Group',
        description: 'Group for Outdoor Events',
        users: [mockUsers[14], mockUsers[15], mockUsers[16], mockUsers[19]],
    },
    {
        id: 7,
        name: 'Foodie Group',
        description: 'Group for Food Events',
        users: [mockUsers[17], mockUsers[18], mockUsers[19], mockUsers[22]],
    },
    {
        id: 8,
        name: 'Book Club',
        description: 'Group for Literary Events',
        users: [mockUsers[20], mockUsers[21], mockUsers[22], mockUsers[25]],
    },
    {
        id: 9,
        name: 'Wellness Club',
        description: 'Group for Fitness Events',
        users: [mockUsers[23], mockUsers[24], mockUsers[25], mockUsers[28]],
    },
    {
        id: 10,
        name: 'Education Enthusiasts',
        description: 'Group for Educational Seminars',
        users: [mockUsers[26], mockUsers[27], mockUsers[28], mockUsers[2]],
    },
]
